/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.border.LineBorder;

/**
 *
 * @author juan6
 */
public class interfaz_Principal extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    private boolean btnAdminEstado = false;
    private boolean btnCobroEstado = true;
    private boolean btnCorteEstado = false;

    /**
     * Creates new form interfaz_Principal
     */
    public interfaz_Principal() {
        initComponents();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("LavaAutos_DERSPU");
        setLocationRelativeTo(null);
        panelCobro p2 = new panelCobro();
        //[1020, 570]
        p2.setSize(1020, 570);
        p2.setLocation(0, 0);
        
        

        cuerpo.removeAll();
        cuerpo.add(p2, BorderLayout.CENTER);
        cuerpo.revalidate();
        cuerpo.repaint();
        btnCobro.setBorder(new LineBorder(Color.WHITE, 2, rootPaneCheckingEnabled));
        btnCorte.setBorder(null);
        btnAdmin.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        barraTareas = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        secciones = new javax.swing.JPanel();
        btnCobro = new javax.swing.JPanel();
        txtCobro = new javax.swing.JLabel();
        btnCorte = new javax.swing.JPanel();
        txtCorte = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JPanel();
        txtAdmin = new javax.swing.JLabel();
        cabecera = new javax.swing.JPanel();
        paneNombreLA = new javax.swing.JPanel();
        imgNombre = new javax.swing.JLabel();
        bgCabecera = new javax.swing.JLabel();
        cuerpo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraTareas.setBackground(new java.awt.Color(0, 0, 0));
        barraTareas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        barraTareas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraTareasMouseDragged(evt);
            }
        });
        barraTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraTareasMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraTareasLayout = new javax.swing.GroupLayout(barraTareas);
        barraTareas.setLayout(barraTareasLayout);
        barraTareasLayout.setHorizontalGroup(
            barraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraTareasLayout.createSequentialGroup()
                .addGap(0, 1163, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraTareasLayout.setVerticalGroup(
            barraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(barraTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        secciones.setBackground(new java.awt.Color(28, 28, 28));
        secciones.setBorder(null);
        secciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCobro.setBackground(new java.awt.Color(81, 79, 80));
        btnCobro.setBorder(null);
        btnCobro.setOpaque(false);

        txtCobro.setBackground(new java.awt.Color(255, 255, 255));
        txtCobro.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        txtCobro.setForeground(new java.awt.Color(255, 255, 255));
        txtCobro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/carro (1).png"))); // NOI18N
        txtCobro.setText(" COBRO   ");
        txtCobro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCobroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCobroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCobroMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCobroLayout = new javax.swing.GroupLayout(btnCobro);
        btnCobro.setLayout(btnCobroLayout);
        btnCobroLayout.setHorizontalGroup(
            btnCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnCobroLayout.setVerticalGroup(
            btnCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        secciones.add(btnCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 50));

        btnCorte.setBackground(new java.awt.Color(81, 79, 80));
        btnCorte.setBorder(null);
        btnCorte.setOpaque(false);

        txtCorte.setBackground(new java.awt.Color(255, 255, 255));
        txtCorte.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        txtCorte.setForeground(new java.awt.Color(255, 255, 255));
        txtCorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/corte (1).png"))); // NOI18N
        txtCorte.setText(" CORTE   ");
        txtCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCorteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCorteLayout = new javax.swing.GroupLayout(btnCorte);
        btnCorte.setLayout(btnCorteLayout);
        btnCorteLayout.setHorizontalGroup(
            btnCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCorte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnCorteLayout.setVerticalGroup(
            btnCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCorte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        secciones.add(btnCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 180, 50));

        btnAdmin.setBackground(new java.awt.Color(81, 79, 80));
        btnAdmin.setBorder(null);
        btnAdmin.setOpaque(false);

        txtAdmin.setBackground(new java.awt.Color(255, 255, 255));
        txtAdmin.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        txtAdmin.setForeground(new java.awt.Color(255, 255, 255));
        txtAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/admin (1).png"))); // NOI18N
        txtAdmin.setText(" ADMIN   ");
        txtAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAdminMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnAdminLayout = new javax.swing.GroupLayout(btnAdmin);
        btnAdmin.setLayout(btnAdminLayout);
        btnAdminLayout.setHorizontalGroup(
            btnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnAdminLayout.setVerticalGroup(
            btnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        secciones.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 180, 50));

        bg.add(secciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 670));

        cabecera.setBackground(new java.awt.Color(17, 17, 17));
        cabecera.setBorder(null);
        cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneNombreLA.setBackground(new java.awt.Color(255, 255, 255));
        paneNombreLA.setOpaque(false);

        imgNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/texto2.png"))); // NOI18N

        javax.swing.GroupLayout paneNombreLALayout = new javax.swing.GroupLayout(paneNombreLA);
        paneNombreLA.setLayout(paneNombreLALayout);
        paneNombreLALayout.setHorizontalGroup(
            paneNombreLALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        paneNombreLALayout.setVerticalGroup(
            paneNombreLALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        cabecera.add(paneNombreLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 390, 100));

        bgCabecera.setBackground(new java.awt.Color(51, 51, 51));
        bgCabecera.setToolTipText("");
        cabecera.add(bgCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 100));

        bg.add(cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 1020, 100));

        cuerpo.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo.setBorder(null);

        javax.swing.GroupLayout cuerpoLayout = new javax.swing.GroupLayout(cuerpo);
        cuerpo.setLayout(cuerpoLayout);
        cuerpoLayout.setHorizontalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        cuerpoLayout.setVerticalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        bg.add(cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 1020, 570));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked
       
    private void barraTareasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTareasMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraTareasMousePressed

    private void barraTareasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTareasMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraTareasMouseDragged
            
    private void txtAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminMousePressed
        btnCobroEstado = false;
        btnCorteEstado = false;
        btnAdminEstado = true;
        btnCobro.setBorder(null);
        btnCorte.setBorder(null);
        btnAdmin.setBorder(new LineBorder(Color.WHITE, 2, rootPaneCheckingEnabled));
        loginAdmin p1 = new loginAdmin();
        //[1020, 570]
        p1.setSize(1020, 570);
        p1.setLocation(0, 0);

        cuerpo.removeAll();
        cuerpo.add(p1, BorderLayout.CENTER);
        cuerpo.revalidate();
        cuerpo.repaint();
    }//GEN-LAST:event_txtAdminMousePressed

    private void txtCobroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCobroMousePressed
        btnCobroEstado = true;
        btnCorteEstado = false;
        btnAdminEstado = false;
        btnCobro.setBorder(new LineBorder(Color.WHITE, 2, rootPaneCheckingEnabled));
        btnCorte.setBorder(null);
        btnAdmin.setBorder(null);
        panelCobro p2 = new panelCobro();
        //[1020, 570]
        p2.setSize(1020, 570);
        p2.setLocation(0, 0);

        cuerpo.removeAll();
        cuerpo.add(p2, BorderLayout.CENTER);
        cuerpo.revalidate();
        cuerpo.repaint();
    }//GEN-LAST:event_txtCobroMousePressed

    private void txtCobroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCobroMouseEntered
        btnCobro.setBorder(new LineBorder(Color.WHITE, 2, rootPaneCheckingEnabled));

    }//GEN-LAST:event_txtCobroMouseEntered

    private void txtCobroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCobroMouseExited
        if (btnCobroEstado != true) {
            btnCobro.setBorder(null);
        }

    }//GEN-LAST:event_txtCobroMouseExited

    private void txtCorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorteMouseEntered
        btnCorte.setBorder(new LineBorder(Color.WHITE, 2, rootPaneCheckingEnabled));
    }//GEN-LAST:event_txtCorteMouseEntered

    private void txtCorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorteMouseExited
        if (btnCorteEstado != true) {
            btnCorte.setBorder(null);
        }

    }//GEN-LAST:event_txtCorteMouseExited

    private void txtAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminMouseEntered
        btnAdmin.setBorder(new LineBorder(Color.WHITE, 2, rootPaneCheckingEnabled));
    }//GEN-LAST:event_txtAdminMouseEntered

    private void txtAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminMouseExited
        if (btnAdminEstado != true){
            btnAdmin.setBorder(null);
        }
    }//GEN-LAST:event_txtAdminMouseExited

    private void txtCorteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorteMousePressed
        btnCobroEstado = false;
        btnCorteEstado = true;
        btnAdminEstado = false;
        btnCobro.setBorder(null);
        btnCorte.setBorder(new LineBorder(Color.WHITE, 2, rootPaneCheckingEnabled));
        btnAdmin.setBorder(null);
        panelCorte p3 = new panelCorte();
        //[1020, 570]
        p3.setSize(1020, 570);
        p3.setLocation(0, 0);

        cuerpo.removeAll();
        cuerpo.add(p3, BorderLayout.CENTER);
        cuerpo.revalidate();
        cuerpo.repaint();
    }//GEN-LAST:event_txtCorteMousePressed

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        btnSalir.setBackground(Color.RED);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        btnSalir.setBackground(Color.BLACK);
    }//GEN-LAST:event_txtSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraTareas;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgCabecera;
    private javax.swing.JPanel btnAdmin;
    private javax.swing.JPanel btnCobro;
    private javax.swing.JPanel btnCorte;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JLabel imgNombre;
    private javax.swing.JPanel paneNombreLA;
    private javax.swing.JPanel secciones;
    private javax.swing.JLabel txtAdmin;
    private javax.swing.JLabel txtCobro;
    private javax.swing.JLabel txtCorte;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
