/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controllers.AdministradorJpaController;
import EntityClasses.Administrador;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author juan6
 */
public class loginAdmin extends javax.swing.JPanel {

    //private Administrador admin;
    private AdministradorJpaController cAdmin;
    private List<Administrador> admins;
    private boolean existencia = false;

    /**
     * Creates new form loginAdmin
     */
    public loginAdmin() {
        initComponents();

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("LavaAutos_DERSPU");
        cAdmin = new AdministradorJpaController(emf);
        admins = cAdmin.findAdministradorEntities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreUsuarioTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnAceptarIS = new javax.swing.JPanel();
        txtAceptarIS = new javax.swing.JLabel();
        panelIco = new javax.swing.JPanel();
        txtIco = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtIcoLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mensajeLogin = new javax.swing.JLabel();
        olvidoContra = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        cuerpo.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo.setBorder(null);
        cuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar sesión");
        cuerpo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("Usuario: ");
        cuerpo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        nombreUsuarioTxt.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        nombreUsuarioTxt.setForeground(new java.awt.Color(153, 153, 153));
        nombreUsuarioTxt.setText("Ingrese su nombre de usuario");
        nombreUsuarioTxt.setBorder(null);
        nombreUsuarioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreUsuarioTxtMousePressed(evt);
            }
        });
        nombreUsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTxtActionPerformed(evt);
            }
        });
        cuerpo.add(nombreUsuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 290, -1));
        cuerpo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 290, 10));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("Contraseña: ");
        cuerpo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        passwordTxt.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(153, 153, 153));
        passwordTxt.setText("********");
        passwordTxt.setBorder(null);
        passwordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTxtMousePressed(evt);
            }
        });
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        cuerpo.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 290, -1));
        cuerpo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 290, 10));

        btnAceptarIS.setBackground(new java.awt.Color(102, 204, 255));
        btnAceptarIS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 17, 17)));
        btnAceptarIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarISMouseClicked(evt);
            }
        });

        txtAceptarIS.setBackground(new java.awt.Color(255, 255, 255));
        txtAceptarIS.setFont(new java.awt.Font("Roboto Condensed", 1, 16)); // NOI18N
        txtAceptarIS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAceptarIS.setText("Aceptar");
        txtAceptarIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAceptarISMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAceptarISMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAceptarISMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAceptarISLayout = new javax.swing.GroupLayout(btnAceptarIS);
        btnAceptarIS.setLayout(btnAceptarISLayout);
        btnAceptarISLayout.setHorizontalGroup(
            btnAceptarISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAceptarIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        btnAceptarISLayout.setVerticalGroup(
            btnAceptarISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAceptarIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        cuerpo.add(btnAceptarIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, -1, -1));

        panelIco.setBackground(new java.awt.Color(255, 255, 255));

        txtIco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Icono.png"))); // NOI18N

        javax.swing.GroupLayout panelIcoLayout = new javax.swing.GroupLayout(panelIco);
        panelIco.setLayout(panelIcoLayout);
        panelIcoLayout.setHorizontalGroup(
            panelIcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIcoLayout.createSequentialGroup()
                .addComponent(txtIco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelIcoLayout.setVerticalGroup(
            panelIcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIcoLayout.createSequentialGroup()
                .addComponent(txtIco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cuerpo.add(panelIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtIcoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/loginAdmin3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtIcoLogin)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIcoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cuerpo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 570));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/texto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        cuerpo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 250, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/person (1).png"))); // NOI18N
        cuerpo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 120, 110));

        mensajeLogin.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        mensajeLogin.setForeground(new java.awt.Color(255, 0, 0));
        mensajeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuerpo.add(mensajeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 530, 400, 30));

        olvidoContra.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        olvidoContra.setForeground(new java.awt.Color(0, 0, 153));
        olvidoContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        olvidoContra.setText("¿Olvidó su contraseña?");
        olvidoContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        olvidoContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olvidoContraMouseClicked(evt);
            }
        });
        cuerpo.add(olvidoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTxtActionPerformed

    private void nombreUsuarioTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtMousePressed
        if (nombreUsuarioTxt.getText().equals("Ingrese su nombre de usuario")) {
            nombreUsuarioTxt.setText("");
            nombreUsuarioTxt.setForeground(Color.black);
        }
        if (String.valueOf(passwordTxt.getPassword()).isEmpty()) {
            passwordTxt.setText("********");
            passwordTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombreUsuarioTxtMousePressed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void passwordTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTxtMousePressed
        if (String.valueOf(passwordTxt.getPassword()).equals("********")) {
            passwordTxt.setText("");
            passwordTxt.setForeground(Color.black);
        }
        if (nombreUsuarioTxt.getText().isEmpty()) {
            nombreUsuarioTxt.setText("Ingrese su nombre de usuario");
            nombreUsuarioTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passwordTxtMousePressed

    private void txtAceptarISMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAceptarISMouseEntered
        btnAceptarIS.setBackground(new Color(112, 214, 255));
    }//GEN-LAST:event_txtAceptarISMouseEntered

    private void txtAceptarISMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAceptarISMouseExited
        btnAceptarIS.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_txtAceptarISMouseExited


    private void txtAceptarISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAceptarISMouseClicked
        //Aqui se colocara la validación de usuario administrador
        try{
        System.out.println("Parte 1");
        if (nombreUsuarioTxt.getText().equalsIgnoreCase("Ingrese su nombre de usuario") || nombreUsuarioTxt.getText().equalsIgnoreCase("")
                || passwordTxt.getPassword().toString().equalsIgnoreCase("") || passwordTxt.getPassword().toString().equalsIgnoreCase("********")) {
            
            System.out.println("Primer if");
            mensajeLogin.setText("Ingrese credenciales");
            repaint();
        } else {
            for (int a = 0; a < admins.size(); a++) {
                //System.out.println("Si entro al for" + admins.get(a).getUsuarioidUsuario().getNombre() + passwordTxt.getPassword().toString());
                if (nombreUsuarioTxt.getText().equalsIgnoreCase(admins.get(a).getUsuarioidUsuario().getNombre())
                        && String.valueOf(passwordTxt.getPassword()).equalsIgnoreCase(admins.get(a).getContrasenia())) {
                    mensajeLogin.setText(" ");
                    //mensajeLogin.setText("Si ingreso");
                    
                    panelAdmin p2 = new panelAdmin();

                    p2.setSize(1020, 570);
                    p2.setLocation(0, 0);

                    this.removeAll();
                    repaint();
                    this.add(p2, BorderLayout.CENTER);
                    this.revalidate();
                    this.repaint();
                }else{
                    if(a == (admins.size() - 1)){
                        mensajeLogin.setText("Credenciales incorrectas");
                        repaint();
                    }
                }
            }
        }
        }catch(Exception E){
            mensajeLogin.setText(E.getMessage());
            nombreUsuarioTxt.setText(E.getMessage());
            repaint();
        }


    }//GEN-LAST:event_txtAceptarISMouseClicked

    private void btnAceptarISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarISMouseClicked
        //Aqui se colocara la validación de usuario administrador
        System.out.println("Parte 1");
        if (nombreUsuarioTxt.getText().equalsIgnoreCase("Ingrese su nombre de usuario") || nombreUsuarioTxt.getText().equalsIgnoreCase("")
                || passwordTxt.getPassword().toString().equalsIgnoreCase("") || passwordTxt.getPassword().toString().equalsIgnoreCase("********")) {
            
            System.out.println("Primer if");
            mensajeLogin.setText("Ingrese credenciales");
            repaint();
        } else {
            for (int a = 0; a < admins.size(); a++) {
                System.out.println("Si entro al for" + admins.get(a).getUsuarioidUsuario().getNombre() + passwordTxt.getPassword().toString());
                if (nombreUsuarioTxt.getText().equalsIgnoreCase(admins.get(a).getUsuarioidUsuario().getNombre())
                        && String.valueOf(passwordTxt.getPassword()).equalsIgnoreCase(admins.get(a).getContrasenia())) {
                    System.out.println(" " + a);
                    existencia = true;
                    panelAdmin p2 = new panelAdmin();

                    p2.setSize(1020, 570);
                    p2.setLocation(0, 0);

                    this.removeAll();
                    this.add(p2, BorderLayout.CENTER);
                    this.revalidate();
                    this.repaint();
                }else{
                    if(a == (admins.size() - 1)){
                        mensajeLogin.setText("Credenciales incorrectas");
                        repaint();
                    }
                }
            }
        }

    }//GEN-LAST:event_btnAceptarISMouseClicked

    private void olvidoContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvidoContraMouseClicked
        ventanaRecuperarContraseña ae = new ventanaRecuperarContraseña(new javax.swing.JFrame(), true);
        
    }//GEN-LAST:event_olvidoContraMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAceptarIS;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensajeLogin;
    private javax.swing.JTextField nombreUsuarioTxt;
    private javax.swing.JLabel olvidoContra;
    private javax.swing.JPanel panelIco;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel txtAceptarIS;
    private javax.swing.JLabel txtIco;
    private javax.swing.JLabel txtIcoLogin;
    // End of variables declaration//GEN-END:variables
}
