/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author juan6
 */
public class panelAdmin extends javax.swing.JPanel {

    private boolean btnAdminUEstado = false;
    private boolean btnPrecioEstado = true;
    private boolean btnPagoEstado = false;

    /**
     * Creates new form panelAdmin
     */
    public panelAdmin() {
        initComponents();
        btnAdminUEstado = true;
        btnPagoEstado = false;
        btnPrecioEstado = false;
        btnUsuariosTP.setBorder(new LineBorder(Color.WHITE, 2, true));
        btnPreciosTP.setBorder(null);
        btnPagoTP.setBorder(null);
        panelUsuario p2 = new panelUsuario();
        //[1020, 570]
        p2.setSize(1020, 540);
        p2.setLocation(0, 0);

        cuerpoTabbedPane.removeAll();
        cuerpoTabbedPane.add(p2, BorderLayout.CENTER);
        cuerpoTabbedPane.revalidate();
        cuerpoTabbedPane.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpoTabbedPane = new javax.swing.JPanel();
        btnUsuariosTP = new javax.swing.JPanel();
        txtAdminUsua = new javax.swing.JLabel();
        btnPreciosTP = new javax.swing.JPanel();
        txtAdminPrecios = new javax.swing.JLabel();
        btnPagoTP = new javax.swing.JPanel();
        txtAdminPagos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuerpoTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        cuerpoTabbedPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        javax.swing.GroupLayout cuerpoTabbedPaneLayout = new javax.swing.GroupLayout(cuerpoTabbedPane);
        cuerpoTabbedPane.setLayout(cuerpoTabbedPaneLayout);
        cuerpoTabbedPaneLayout.setHorizontalGroup(
            cuerpoTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        cuerpoTabbedPaneLayout.setVerticalGroup(
            cuerpoTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        add(cuerpoTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1020, 540));

        btnUsuariosTP.setBackground(new java.awt.Color(153, 153, 255));

        txtAdminUsua.setBackground(new java.awt.Color(255, 255, 255));
        txtAdminUsua.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        txtAdminUsua.setForeground(new java.awt.Color(255, 255, 255));
        txtAdminUsua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdminUsua.setText("Administrar usuarios");
        txtAdminUsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAdminUsuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAdminUsuaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAdminUsuaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnUsuariosTPLayout = new javax.swing.GroupLayout(btnUsuariosTP);
        btnUsuariosTP.setLayout(btnUsuariosTPLayout);
        btnUsuariosTPLayout.setHorizontalGroup(
            btnUsuariosTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdminUsua, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnUsuariosTPLayout.setVerticalGroup(
            btnUsuariosTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdminUsua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(btnUsuariosTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        btnPreciosTP.setBackground(new java.awt.Color(153, 153, 255));

        txtAdminPrecios.setBackground(new java.awt.Color(255, 255, 255));
        txtAdminPrecios.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        txtAdminPrecios.setForeground(new java.awt.Color(255, 255, 255));
        txtAdminPrecios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdminPrecios.setText("Administrar precios");
        txtAdminPrecios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAdminPreciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAdminPreciosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAdminPreciosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnPreciosTPLayout = new javax.swing.GroupLayout(btnPreciosTP);
        btnPreciosTP.setLayout(btnPreciosTPLayout);
        btnPreciosTPLayout.setHorizontalGroup(
            btnPreciosTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdminPrecios, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnPreciosTPLayout.setVerticalGroup(
            btnPreciosTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdminPrecios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(btnPreciosTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 30));

        btnPagoTP.setBackground(new java.awt.Color(153, 153, 255));

        txtAdminPagos.setBackground(new java.awt.Color(255, 255, 255));
        txtAdminPagos.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        txtAdminPagos.setForeground(new java.awt.Color(255, 255, 255));
        txtAdminPagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdminPagos.setText("Pago de sueldos");
        txtAdminPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAdminPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAdminPagosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAdminPagosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnPagoTPLayout = new javax.swing.GroupLayout(btnPagoTP);
        btnPagoTP.setLayout(btnPagoTPLayout);
        btnPagoTPLayout.setHorizontalGroup(
            btnPagoTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdminPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnPagoTPLayout.setVerticalGroup(
            btnPagoTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdminPagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(btnPagoTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    

    private void txtAdminUsuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminUsuaMouseEntered
        btnUsuariosTP.setBorder(new LineBorder(Color.WHITE, 2, true));
    }//GEN-LAST:event_txtAdminUsuaMouseEntered

    private void txtAdminUsuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminUsuaMouseExited
        if (btnAdminUEstado != true) {
            btnUsuariosTP.setBorder(null);
        }
    }//GEN-LAST:event_txtAdminUsuaMouseExited

    private void txtAdminUsuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminUsuaMousePressed
        btnAdminUEstado = true;
        btnPagoEstado = false;
        btnPrecioEstado = false;
        btnUsuariosTP.setBorder(new LineBorder(Color.WHITE, 2, true));
        btnPreciosTP.setBorder(null);
        btnPagoTP.setBorder(null);
        panelUsuario p2 = new panelUsuario();
        //[1020, 570]
        p2.setSize(1020, 540);
        p2.setLocation(0, 0);

        cuerpoTabbedPane.removeAll();
        cuerpoTabbedPane.add(p2, BorderLayout.CENTER);
        cuerpoTabbedPane.revalidate();
        cuerpoTabbedPane.repaint();
    }//GEN-LAST:event_txtAdminUsuaMousePressed

    private void txtAdminPreciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminPreciosMouseEntered
        btnPreciosTP.setBorder(new LineBorder(Color.WHITE, 2, true));
    }//GEN-LAST:event_txtAdminPreciosMouseEntered

    private void txtAdminPreciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminPreciosMouseExited
        if (btnPrecioEstado != true) {
            btnPreciosTP.setBorder(null);
        }
    }//GEN-LAST:event_txtAdminPreciosMouseExited

    private void txtAdminPreciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminPreciosMousePressed
        btnAdminUEstado = false;
        btnPagoEstado = false;
        btnPrecioEstado = true;
        btnPreciosTP.setBorder(new LineBorder(Color.WHITE, 2, true));
        btnUsuariosTP.setBorder(null);
        btnPagoTP.setBorder(null);
        
        panelPrecio p2 = new panelPrecio();
        //[1020, 540]
        p2.setSize(1020, 540);
        p2.setLocation(0, 0);

        cuerpoTabbedPane.removeAll();
        cuerpoTabbedPane.add(p2, BorderLayout.CENTER);
        cuerpoTabbedPane.revalidate();
        cuerpoTabbedPane.repaint();
    }//GEN-LAST:event_txtAdminPreciosMousePressed

    private void txtAdminPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminPagosMouseEntered
        btnPagoTP.setBorder(new LineBorder(Color.WHITE, 2, true));
    }//GEN-LAST:event_txtAdminPagosMouseEntered

    private void txtAdminPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminPagosMouseExited
        if (btnPagoEstado != true) {
            btnPagoTP.setBorder(null);
        }
    }//GEN-LAST:event_txtAdminPagosMouseExited

    private void txtAdminPagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdminPagosMousePressed
        btnAdminUEstado = false;
        btnPagoEstado = true;
        btnPrecioEstado = false;
        btnPagoTP.setBorder(new LineBorder(Color.WHITE, 2, true));
        btnUsuariosTP.setBorder(null);
        btnPreciosTP.setBorder(null);
        
        panelPago p2 = new panelPago();
        //[1020, 540]
        p2.setSize(1020, 540);
        p2.setLocation(0, 0);

        cuerpoTabbedPane.removeAll();
        cuerpoTabbedPane.add(p2, BorderLayout.CENTER);
        cuerpoTabbedPane.revalidate();
        cuerpoTabbedPane.repaint();
        
    }//GEN-LAST:event_txtAdminPagosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPagoTP;
    private javax.swing.JPanel btnPreciosTP;
    private javax.swing.JPanel btnUsuariosTP;
    private javax.swing.JPanel cuerpoTabbedPane;
    private javax.swing.JLabel txtAdminPagos;
    private javax.swing.JLabel txtAdminPrecios;
    private javax.swing.JLabel txtAdminUsua;
    // End of variables declaration//GEN-END:variables
}
